In [11]:
# In Python, the standard library for this is mlxtend (Machine Learning Extensions), 
# as Scikit-learn does not provide a direct implementation for Apriori.

In [1]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [2]:
dataset = [
    ['Milk', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
    ['Dill', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
    ['Milk', 'Apple', 'Kidney Beans', 'Eggs'],
    ['Milk', 'Unicorn', 'Corn', 'Kidney Beans', 'Yogurt'],
    ['Corn', 'Onion', 'Onion', 'Kidney Beans', 'Ice cream', 'Eggs']
]

In [3]:
# Apriori requires a DataFrame where items are columns and values are True/False (or 1/0)
te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)
df = pd.DataFrame(te_ary, columns=te.columns_)

In [5]:
df.head(2)

,Apple,Corn,Dill,Eggs,Ice cream,Kidney Beans,Milk,Nutmeg,Onion,Unicorn,Yogurt
0,False,False,False,True,False,True,True,True,True,False,True
1,False,False,True,True,False,True,False,True,True,False,True

In [6]:
# first we will be finding frequent itemsets
frequent_itemsets = apriori(df, min_support=0.6, use_colnames=True)
frequent_itemsets

    support                     itemsets
0       0.8                       (Eggs)
1       1.0               (Kidney Beans)
2       0.6                       (Milk)
3       0.6                      (Onion)
4       0.6                     (Yogurt)
5       0.8         (Eggs, Kidney Beans)
6       0.6                (Eggs, Onion)
7       0.6         (Milk, Kidney Beans)
8       0.6        (Kidney Beans, Onion)
9       0.6       (Kidney Beans, Yogurt)
10      0.6  (Eggs, Kidney Beans, Onion)

In [12]:
# now we will be finding most freqent based on threshol/confidence
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)

C:\Users\DELL\miniconda3\envs\campusx\Lib\site-packages\mlxtend\frequent_patterns\association_rules.py:186: RuntimeWarning: invalid value encountered in divide
  cert_metric = np.where(certainty_denom == 0, 0, certainty_num / certainty_denom)

In [13]:
print("Association Rules:")
print(rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']])

Association Rules:
              antecedents            consequents  support  confidence  lift
0                  (Eggs)         (Kidney Beans)      0.8        1.00  1.00
1          (Kidney Beans)                 (Eggs)      0.8        0.80  1.00
2                  (Eggs)                (Onion)      0.6        0.75  1.25
3                 (Onion)                 (Eggs)      0.6        1.00  1.25
4                  (Milk)         (Kidney Beans)      0.6        1.00  1.00
5          (Kidney Beans)                 (Milk)      0.6        0.60  1.00
6          (Kidney Beans)                (Onion)      0.6        0.60  1.00
7                 (Onion)         (Kidney Beans)      0.6        1.00  1.00
8          (Kidney Beans)               (Yogurt)      0.6        0.60  1.00
9                (Yogurt)         (Kidney Beans)      0.6        1.00  1.00
10   (Eggs, Kidney Beans)                (Onion)      0.6        0.75  1.25
11          (Eggs, Onion)         (Kidney Beans)      0.6        1.00  1.00
12  (Kidney Beans, Onion)                 (Eggs)      0.6        1.00  1.25
13                 (Eggs)  (Kidney Beans, Onion)      0.6        0.75  1.25
14         (Kidney Beans)          (Eggs, Onion)      0.6        0.60  1.00
15                (Onion)   (Eggs, Kidney Beans)      0.6        1.00  1.25

In [14]:
# we are getting all patterns which are more than threshold of lif = 1